name: CI
'on':
  workflow_dispatch: null
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '!.github/workflows/check.yml'
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '!.github/workflows/ci.yml'
concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}'
  cancel-in-progress: '${{ github.ref_name != ''main'' }}'
env:
  CARGO_INCREMENTAL: 0
jobs:
  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: crate-ci/typos@v1.23.5
        with:
          files: .
